### ISSUE TITLE
io.js (old node versions) bug !! 

### ISSUE THREAD

**Issue by 3imed-jaberi** [jasongin/nvs#154]
I used travis ci for my project with this config: 

```yml
os:
  - windows
  - linux
  - osx
language: node_js
node_js:
  - 0.10
  - 0.12
  - 1.8
  - 2.5
  - 3.3
  - 4.9
  - 5.12
  - 6.17
  - 7.10
  - 8.16
  - 9.11
  - 10.15
  - 11.15
  - 12.3
  - 'lts/*'
  - 'node'
...
```

All versions succeeded on all platforms except 3 versions on Windows ( 1.8, 2.5 and 3.3 ).
There is a notification that the NODE version isn't in the remote 🤔 !!
check [here](https://nodejs.org/en/download/releases/).

screenshots: 

###### success : 

![image](https://user-images.githubusercontent.com/43971542/73382843-92158e00-42c8-11ea-9d71-45230cda0733.png)

###### failed: 
 - 1.8 : 

![windows-node1.8](https://user-images.githubusercontent.com/43971542/73381397-f08d3d00-42c5-11ea-8b0e-c4bb7ad7893a.png)

- 2.5: 

![windows-node2.5](https://user-images.githubusercontent.com/43971542/73381458-11ee2900-42c6-11ea-80f6-6fcc0b0a8116.png)

- 3.3: 

![windows-node3.3](https://user-images.githubusercontent.com/43971542/73382234-71990400-42c7-11ea-8b8e-4fc7372ef858.png)
