### ISSUE TITLE
Install via Ansible?

### ISSUE THREAD

**Issue by SturmB** [jasongin/nvs#176]
What is the best way to install NVS via Ansible?

So far, I have the following in my playbook:

```yaml
    - name: See if NVS is already installed
      lineinfile:
        path: ~/.zshrc
        line: export NVS_HOME="$HOME/.nvs"
        state: present
      check_mode: true
      register: zshrc

    - name: Clone the NVS repo
      git:
        repo: https://github.com/jasongin/nvs
        dest: "$NVS_HOME"
        version: v1.6.0
      ignore_errors: true
      when: (zshrc is changed) or (zshrc is failed)

    - name: Ensure NVS is installed
      shell: ". \"$NVS_HOME/nvs.sh\" install"
      when: (zshrc is changed) or (zshrc is failed)
```

However, the third task fails due to `nvs.sh` not being executable, I guess?

```
"stderr": "/bin/sh: 1: .: Can't open ~/.nvs/nvs.sh"
```

What else should I try?
